### ISSUE TITLE
image-helpers renderImage is slow

### ISSUE THREAD

**Issue by Fauny** [justadudewhohacks/opencv-electron#2] opened 2017-12-01 17:10 UTC
I'm making a live-video process test project,  use image-helpers' renderImage to draw the captured frames to canvas,  then I find out this function is too slow.

when I use cv.imshow, it's very fast, but the window cannot be controlled.

**Comment by justadudewhohacks** [comment] 2017-12-01 17:34
What is the size of your frames? The bottleneck could either result from mat.getData or context.putImageData. Not sure at this point how to speed it up even more.

**Comment by Fauny** [comment] 2017-12-02 02:57
My frames is full HD[1080,1920], I've resized it to  [360, 640], it's still slow.
but when i use cv.imshow, it works fine at the original size.

**Comment by justadudewhohacks** [comment] 2017-12-02 10:57
Strange  [360, 640] is actually pretty small smized. Did you measure the time per frame that it needs to draw the frame or did you just notice that it looks laggy?

**Comment by Fauny** [comment] 2017-12-03 10:36
It takes 125~160 ms per frame.

maybe it's an electron(Chromium) bug, my project bound with the latest Electron: 1.7.9 Chromium: 58.0.3029.110

**Comment by justadudewhohacks** [comment] 2017-12-03 11:56
It's not a bug you are right. I just tried with an 800x320 image and found the bottleneck. renderImage on average took about 130ms with spending roughly 125ms in mat.getData() lol.. . Then I remembered that in getData() I just return a node buffer with the copy of the data. Probably it's just the memcpy that takes so much time.

I will try to find a way to pass the mat data to nodejs without having to copy it.

**Comment by justadudewhohacks** [comment] 2017-12-03 14:43
I just tried to figure out what's going on and the results are very unfortunate. Turns out that with electron returning a node buffer from a native addon is very slow. An equivalent node.js script returns the buffer of the same image data in less then a milisecond whereas with electron it takes like 100ms+.

I am not sure why this is, might be due to electron-rebuild. Unfortunately I am not that familar with the internals of electron and what the implications of electron-rebuild are, so I can't say what's going on here.

**Comment by justadudewhohacks** [comment] 2017-12-08 07:57
Maybe you can have a look at the referenced issue above. There is someone using nw.js, which is a similar framework to electron. Apparently the issue with getData is not present with nw.js. I will try to test this out myself as soon as I have some time.

**Comment by nkint** [comment] 2017-12-19 14:38
any news on this?

**Comment by justadudewhohacks** [comment] 2017-12-19 15:35
Still a problem with electron. I didn't get any answer on my issue at electron-rebuild yet. I will try my luck opening an issue at electron.

**Comment by justadudewhohacks** [comment] 2018-01-19 07:50
Fixed with opencv4nodejs v2.37.1. The solution is to require the module directly and not via remote, which will cause the buffer to be serialized.

**Closed as completed by justadudewhohacks** 2018-01-19 07:50 UTC
